In [ ]:
from google.colab import files
uploades = files.upload()

Saving cases_merged.csv to cases_merged.csv


In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("cases_merged.csv")
data = df.copy()

In [ ]:
# classification
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

X = data.drop(['criminal'], axis=1)
y = data['criminal']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# random forest classifier
rfc = RandomForestClassifier(n_estimators=100, random_state=42)
rfc.fit(X_train, y_train)
y_pred = rfc.predict(X_test)

In [ ]:
df.head()

judge_position  female_defendant  female_petitioner  type_name  \
0               0                 0                  0       1903   
1               1                 0                  1       1907   
2               1                 0                  1       5736   
3               2                 0                  0       5736   
4               2                 0                  0       5274   

   purpose_name  disp_name    act  criminal  
0          4366         22  17353         1  
1          5487         26   4759         1  
2          4919         45  17353         1  
3          2821         26  17353         1  
4          2821         25  17353         1

In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

# confusion matrix
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

0.999995855300242
[[195865      1]
 [     0  45406]]


In [ ]:
from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

In [ ]:
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

1.0
[[195866      0]
 [     0  45406]]


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

In [ ]:
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.9958718790410822
[[195394    472]
 [   524  44882]]


In [ ]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

In [ ]:
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.9947652442057098
[[195269    597]
 [   666  44740]]
